name: Deploy to Web App

on:
  workflow_dispatch:

env:
  APP_PATH: './src/Web2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Container
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build ${{ env.APP_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{ env.APP_PATH }}/myapp

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.APP_PATH }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build jobs
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      
      - name: Deploy to Web app
        id: deploy-to-webAppName
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-telescope'
          slot-name: 'Production'
          package: .
      
      - name: logout
        run: |
          az logout
